# Generated by Django 5.2 on 2025-04-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_or_sentence', models.CharField(max_length=255, unique=True)),
                ('explanation', models.TextField()),
            ],
        ),
    ]
